version: '3.4'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  print-me-at:
    image: print-me-at:latest
    environment:
      REDIS_ADDRESS: redis://redis:6379
    depends_on:
      - redis
    links:
      - redis
    ports:
      - 8080:8080
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 5s
      timeout: 10s
      retries: 100
      start_period: 40s
    restart: always
