// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	models "github.com/PatrickKvartsaniy/print-me-at/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddNewTask mocks base method
func (m *MockRepository) AddNewTask(msg models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTask", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewTask indicates an expected call of AddNewTask
func (mr *MockRepositoryMockRecorder) AddNewTask(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTask", reflect.TypeOf((*MockRepository)(nil).AddNewTask), msg)
}

// Poll mocks base method
func (m *MockRepository) Poll(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Poll", ctx)
}

// Poll indicates an expected call of Poll
func (mr *MockRepositoryMockRecorder) Poll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockRepository)(nil).Poll), ctx)
}
